
[default.extend-identifiers]
# Typo in CubeProgrammer API symbol
writeCortexRegistres = "writeCortexRegistres"

[files]
extend-exclude = [
    "stm32cubeprogrammer-sys/include",
    "stm32cubeprogrammer-sys/src/bindings_linux.rs",
    "stm32cubeprogrammer-sys/src/bindings_windows.rs",
]
